# This is a basic workflow to help you get started with Actions

name: TestActions

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # actionsを実行する条件
    # プルリクエストのタイトルに [WT] または [WIP]が含まれていない
    # または with out testing のラベルが付与されていない
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'with out testing') && !contains(fromJSON('["[WT]", "[WIP]"]'), github.event.pull_request.title) }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # show pull request title
      - name: Show pull request title
        run: echo ${{ github.event.pull_request.title }}
      
      # show pull request labels name
      # array ではなく、全ての名前を表示する
      - name: Show pull request labels name
        run: echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
      
